CREATE TABLE homework_list (
  id INTEGER primary key generated by default as identity,,
            classId INTEGER REFERENCES school_classes(id) ON DELETE CASCADE NOT NULL,
            classDescription: text,
            schoolClass: text,
            classType: text,
            dueDate: Date,
            dueTime: text,
            priority: text
    
);