drop table if exists homework_list;

CREATE TABLE homework_list (
  homeworkid INTEGER primary key generated by default as identity,,
            classid INTEGER REFERENCES school_classes(id) ON DELETE CASCADE NOT NULL,
            classdescription: text,
            schooldlass: text,
            classtype: text,
            duedate: Date,
            duetime: text,
            priority: text
    
);